version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    environment:
      SONAR_USER_HOME: /tmp/sonar
    steps:
      - checkout

      - run:
          name: Set up Python
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest

      - run:
          name: Run Unit Tests
          command: |
            . venv/bin/activate
            mkdir -p test-results
            pytest --junitxml=test-results/results.xml

      - run:
          name: Run OWASP Dependency-Check
          command: |
            # Install dependencies for Dependency-Check
            sudo apt-get update
            sudo apt-get install -y default-jre
            mkdir -p dependency-check && cd dependency-check
            wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
            unzip dependency-check-8.4.0-release.zip
            ./dependency-check/bin/dependency-check.sh --scan ../ --out .

      - store_artifacts:
          path: dependency-check

      - store_test_results:
          path: test-results

      - run:
          name: Send Email with Reports
          command: |
            # Install mailx (simple email tool)
            sudo apt-get install -y mailutils

            # Configure email settings (edit with your SMTP details)
            FROM_EMAIL="K213579@nu.edu.pk"
            TO_EMAIL="kashmalahashmi1@gmail.com"
            SUBJECT="CircleCI Reports"
            BODY="Please find the attached unit test results and dependency check report."

            # Send email with attached reports
            echo "$BODY" | mailx -s "$SUBJECT" -a test-results/results.xml -a dependency-check/dependency-check-report.html $TO_EMAIL

workflows:
  version: 2
  build:
    jobs:
      - build
