version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    environment:
      SONAR_USER_HOME: /tmp/sonar
    steps:
      - checkout

      # Step 1: Set up Python environment and install dependencies
      - run:
          name: Set up Python
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest

      # Step 2: Run Unit Tests
      - run:
          name: Run Unit Tests
          command: |
            . venv/bin/activate
            mkdir -p test-results
            pytest --junitxml=test-results/results.xml

      # Step 3: Run OWASP Dependency-Check
      - run:
          name: Run OWASP Dependency-Check
          command: |
            # Install dependencies for Dependency-Check
            sudo apt-get update
            sudo apt-get install -y default-jre
            mkdir -p dependency-check && cd dependency-check
            wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
            unzip dependency-check-8.4.0-release.zip
            ./dependency-check/bin/dependency-check.sh --scan ../ --out .

      # Step 4: Install OpenJDK 17 and SonarScanner
      - run:
          name: Install OpenJDK 17 and SonarScanner
          command: |
            # Install OpenJDK 17
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk

            # Verify Java 17 Installation
            java -version  # This should print Java 17 info

            # Install SonarScanner
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
            unzip sonar-scanner-cli-4.8.0.2856-linux.zip
            mv sonar-scanner-4.8.0.2856-linux sonar-scanner

            # Set Java 17 as default for SonarScanner
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH

            # Verify that Java 17 is active
            java -version  # Make sure it prints Java 17 info

      # Step 5: Run SonarCloud Analysis
      - run:
          name: Run SonarCloud Analysis
          command: |
            # Ensure Java 17 is being used for SonarScanner
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH

            # Run SonarScanner
            ./sonar-scanner/bin/sonar-scanner \
              -Dsonar.projectKey=SONAR_PROJECT_KEY \
              -Dsonar.organization=SONAR_ORG \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

      # Step 6: Store dependency check and test results
      - store_artifacts:
          path: dependency-check

      - store_test_results:
          path: test-results

workflows:
  version: 2
  build:
    jobs:
      - build
